name: Build PDF
on:
  push:
    paths:
      - "ebook-asas-pendawaian-elektrik.tex"
      - ".github/workflows/build-pdf.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dante-ev/latex-action@latest
        with:
          root_file: ebook-asas-pendawaian-elektrik.tex
      - uses: actions/upload-artifact@v4
        with:
          name: ebook-asas-pendawaian-elektrik
          path: ebook-asas-pendawaian-elektrik.pdf
